### ISSUE TITLE
As a user, I want to be able to install nodejs, npm and yarn excutable

### ISSUE THREAD

**Issue by blyndusk** [blyndusk/woosh#5]
## Tasks: 
- [ ] Install nodejs and npm
- [ ] Install nodejs and npm without user interaction
- [ ] Install yarn
- [ ] Install yarn without user interaction
